[package]
name = "multiline_parser_pluginlib"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libloading = "0.7"
serde = { version = "^1.0.101", features = ["derive"] }
serde_derive = "1.0.152"